import "@triggerfeed/theme/scss/global.scss";
import "./globals.css";

import Providers from "./providers";

export const metadata = {
  title: "TriggerFeed App",
  description: "Generated by Peri Media Group",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
