import "@triggerfeed/theme/scss/global.scss";

export const metadata = {
  title: "TriggerFeed App",
  description: "Generated by Peri Media Group",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
